### ISSUE TITLE
formatting.py out of sync with sdk 1.7.1

### ISSUE THREAD

**Issue by aburgel** [Khan/gae_mini_profiler#33]
It looks like gae_mini_profiler/unformatter/formatting.py is a copy of appstat's formatting.py. There were some changes in 1.7.1 to how appstats formats stacktraces (including fixing a crash related to classes without names), so now the older version of formatting.py is causing the crash for me.

**Comment by benjaminjkraft** [comment]
Apologies for the delayed response to this issue; the file in question was removed entirely in 1aab7c32, so I'm going to close this.
