### ISSUE TITLE
ui should display datastore ops

### ISSUE THREAD

**Issue by proppy** [Khan/gae_mini_profiler#40]
This is especially useful for optimizing indexes and queries for cost and performance.

This is stored in appstats under:
```
trace.billed_ops_list()
```

**Comment by benjaminjkraft** [comment]
Apologies for the very delayed response to this issue.  We currently display datastore ops in the RPCs section:
![](https://camo.githubusercontent.com/c10f064ef89a3d29b7151689b52e5f1ccca0b0e1/687474703a2f2f692e696d6775722e636f6d2f43323967432e706e67)
If there's something additional you'd like to see, feel free to reopen this issue with additional detail.
