### ISSUE TITLE
Shouldn't the current ID always be stored in thread local?

### ISSUE THREAD

**Issue by cdman** [Khan/gae_mini_profiler#51]
I'm referring to this code: https://github.com/kamens/gae_mini_profiler/blob/master/profiler.py#L47

Since 1.7.6 the GAE SDK dev server is also multi-threaded, so maybe we can have only one code-path here (the one with thread local). And also perhaps we now can use sampling in both production and development.

**Comment by benjaminjkraft** [comment]
Closing for the same reason as #66.
