### ISSUE TITLE
Can we run it standalone?

### ISSUE THREAD

**Issue by kunalgrover05** [Khan/gae_mini_profiler#76]
There are cases where the app engine server is majorly a backend server(in our case, it is a WSGI based RPC service), so what could be a good way to use this? Is it possible to have a continuous stream of logs on a standalone page?

**Comment by kunalgrover05** [comment]
Found something that suits the purpose, Django Silk [link](https://github.com/mtford90/silk), but it needs port from Djagno app to WSGI app. Was partially able to make it work for App engine WSGIs, still pending completion.

**Comment by benjaminjkraft** [comment]
There are a number of profiling solutions out there, depending on what stack you're using.  The GAE mini profiler is really designed to be used in a frontend context, though, so it's probably not your best bet for that.
