### ISSUE TITLE
What is required to make this run with Flask?

### ISSUE THREAD

**Issue by egalpin** [Khan/gae_mini_profiler#86]
Thanks for the work, great project.

I'd ideally like to be able to run this with a Flask (python) app that runs under GAE. I know that's not exactly the focus of the work here, as this repo aims to be generic. Just wondering if others have had success running a flask app through the profiler.

Note: I did find the [flask-gae-mini-profiler repo](https://github.com/passy/flask-gae-mini-profiler) but it's quite out of date it appears

**Comment by benjaminjkraft** [comment]
We use it for Flask -- you should just be able to follow the instructions in the README, except instead of `application = webapp2.WSGIApplication([...])`, you'd just do `application = flask_app.wsgi_app` .  (The mini-profiler's own routes use webapp, but that needn't affect yours.)
